---
# tasks file for roles/python-dev
- name: be sure installed
  yum: name={{item}} state=installed enablerepo=epel
  with_items:
    - python-devel
  when: (ansible_distribution != "Amazon") and
        (ansible_distribution != "RedHat") and
        (ansible_distribution != "Ubuntu")
  ignore_errors: true
  tags: python-dev

- name: be sure python-dev is installed
  apt: name={{item}} state=latest
  with_items:
    - python-dev
  when: (ansible_distribution == "Ubuntu")
  tags: python-dev

