---
# tasks file for python-pip
- name: be sure installed
  yum: name={{item}} state=installed enablerepo=epel
  with_items:
    - python-pip
  when: (ansible_distribution != "Amazon") and
        (ansible_distribution != "RedHat") and
        (ansible_distribution != "Ubuntu")
  ignore_errors: true
  tags: python-pip

- name: be sure python-pip is installed
  apt: name={{item}} state=latest
  with_items:
    - python-pip
  when: (ansible_distribution == "Ubuntu")
  tags: python-pip
