---
# tasks file for cloudmonkey
- name: be sure installed
  pip: name={{item}} state=present
  with_items:
    - cloudmonkey
#  when: (ansible_distribution != "Amazon") and
#        (ansible_distribution != "RedHat") and
#        (ansible_distribution != "Ubuntu")
  ignore_errors: true
  tags: cloudmonkey
