---
# tasks file for vim
- name: be sure installed
  yum: name={{item}} state=installed enablerepo=epel
  with_items:
    - vim-enhanced
  when: (ansible_distribution != "Amazon") and
        (ansible_distribution != "RedHat") and
        (ansible_distribution != "Ubuntu")
  ignore_errors: true
  tags: vim

- name: be sure vim is installed
  apt: name={{item}} state=latest
  with_items:
    - vim
  when: (ansible_distribution == "Ubuntu")
  tags: vim
